#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/realme/nashc

PRODUCT_COPY_FILES += \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_device/audio_device.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_device/audio_device.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_device/common/audio_device.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_device/common/audio_device.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/AudioParamOptions.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/AudioParamOptions.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/AudioParamOptions_vext.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/AudioParamOptions_vext.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/BtInfo_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/BtInfo_AudioParam.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/BtInfo_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/BtInfo_ParamUnitDesc.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/HpImpedance_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/HpImpedance_AudioParam.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/HpImpedance_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/HpImpedance_ParamUnitDesc.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/MicInfo_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/MicInfo_AudioParam.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/MicInfo_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/MicInfo_ParamUnitDesc.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/PlaybackACF_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/PlaybackACF_AudioParam.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/PlaybackACF_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/PlaybackACF_ParamUnitDesc.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/PlaybackDRC_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/PlaybackDRC_AudioParam.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/PlaybackDRC_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/PlaybackDRC_ParamUnitDesc.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/PlaybackHCF_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/PlaybackHCF_AudioParam.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/PlaybackHCF_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/PlaybackHCF_ParamUnitDesc.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/PlaybackVolAna_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/PlaybackVolAna_AudioParam.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/PlaybackVolAna_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/PlaybackVolAna_ParamUnitDesc.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/PlaybackVolDigi_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/PlaybackVolDigi_AudioParam.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/PlaybackVolDigi_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/PlaybackVolDigi_ParamUnitDesc.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/PlaybackVolUI_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/PlaybackVolUI_AudioParam.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/PlaybackVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/PlaybackVolUI_ParamUnitDesc.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/Playback_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/Playback_AudioParam.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/Playback_ParamTreeView.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/Playback_ParamTreeView.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/Playback_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/Playback_ParamUnitDesc.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/RecordDMNR_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/RecordDMNR_AudioParam.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/RecordDMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/RecordDMNR_ParamUnitDesc.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/RecordFIR_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/RecordFIR_AudioParam.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/RecordFIR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/RecordFIR_ParamUnitDesc.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/RecordUI_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/RecordUI_AudioParam.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/RecordUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/RecordUI_ParamUnitDesc.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/RecordVolUI_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/RecordVolUI_AudioParam.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/RecordVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/RecordVolUI_ParamUnitDesc.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/RecordVol_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/RecordVol_AudioParam.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/RecordVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/RecordVol_ParamUnitDesc.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/Record_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/Record_AudioParam.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/Record_ParamTreeView.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/Record_ParamTreeView.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/Record_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/Record_ParamUnitDesc.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/RingbackVolUI_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/RingbackVolUI_AudioParam.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/RingbackVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/RingbackVolUI_ParamUnitDesc.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/RingbackVol_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/RingbackVol_AudioParam.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/RingbackVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/RingbackVol_ParamUnitDesc.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/SmartPa_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/SmartPa_AudioParam.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/SmartPa_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/SmartPa_ParamUnitDesc.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/SoundEnhancement_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/SoundEnhancement_AudioParam.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/SoundEnhancement_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/SoundEnhancement_ParamUnitDesc.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/SpeechDMNR_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/SpeechDMNR_AudioParam.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/SpeechDMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/SpeechDMNR_ParamUnitDesc.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/SpeechEchoRef_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/SpeechEchoRef_AudioParam.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/SpeechEchoRef_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/SpeechEchoRef_ParamUnitDesc.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/SpeechGeneral_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/SpeechGeneral_AudioParam.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/SpeechGeneral_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/SpeechGeneral_ParamUnitDesc.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/SpeechMagiClarity_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/SpeechMagiClarity_AudioParam.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/SpeechMagiClarity_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/SpeechMagiClarity_ParamUnitDesc.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/SpeechNetwork_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/SpeechNetwork_AudioParam.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/SpeechNetwork_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/SpeechNetwork_ParamUnitDesc.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/SpeechUI_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/SpeechUI_AudioParam.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/SpeechUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/SpeechUI_ParamUnitDesc.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/SpeechVolUI_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/SpeechVolUI_AudioParam.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/SpeechVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/SpeechVolUI_ParamUnitDesc.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/SpeechVol_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/SpeechVol_AudioParam.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/SpeechVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/SpeechVol_ParamUnitDesc.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/Speech_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/Speech_AudioParam.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/Speech_ParamTreeView.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/Speech_ParamTreeView.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/Speech_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/Speech_ParamUnitDesc.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/USBCall_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/USBCall_AudioParam.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/USBCall_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/USBCall_ParamUnitDesc.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/USBDevice_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/USBDevice_AudioParam.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/USBDevice_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/USBDevice_ParamUnitDesc.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/Ultrasound_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/Ultrasound_AudioParam.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/Ultrasound_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/Ultrasound_ParamUnitDesc.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/UplinkConfiguration_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/UplinkConfiguration_AudioParam.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/UplinkConfiguration_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/UplinkConfiguration_ParamUnitDesc.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/VoIPDMNR_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VoIPDMNR_AudioParam.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/VoIPDMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VoIPDMNR_ParamUnitDesc.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/VoIPGeneral_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VoIPGeneral_AudioParam.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/VoIPGeneral_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VoIPGeneral_ParamUnitDesc.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/VoIPUI_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VoIPUI_AudioParam.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/VoIPUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VoIPUI_ParamUnitDesc.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/VoIPVolUI_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VoIPVolUI_AudioParam.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/VoIPVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VoIPVolUI_ParamUnitDesc.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/VoIPVol_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VoIPVol_AudioParam.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/VoIPVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VoIPVol_ParamUnitDesc.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/VoIP_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VoIP_AudioParam.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/VoIP_ParamTreeView.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VoIP_ParamTreeView.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/VoIP_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VoIP_ParamUnitDesc.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/VoIPv2DMNR_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VoIPv2DMNR_AudioParam.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/VoIPv2DMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VoIPv2DMNR_ParamUnitDesc.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/VoIPv2General_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VoIPv2General_AudioParam.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/VoIPv2General_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VoIPv2General_ParamUnitDesc.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/VoIPv2UI_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VoIPv2UI_AudioParam.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/VoIPv2UI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VoIPv2UI_ParamUnitDesc.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/VoIPv2_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VoIPv2_AudioParam.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/VoIPv2_ParamTreeView.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VoIPv2_ParamTreeView.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/VoIPv2_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VoIPv2_ParamUnitDesc.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/VoWDspAec_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VoWDspAec_AudioParam.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/VoWDspAec_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VoWDspAec_ParamUnitDesc.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/VoWEngineFeature_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VoWEngineFeature_AudioParam.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/VoWEngineFeature_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VoWEngineFeature_ParamUnitDesc.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/VoWHwVad_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VoWHwVad_AudioParam.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/VoWHwVad_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VoWHwVad_ParamUnitDesc.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/VoWMicSetting_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VoWMicSetting_AudioParam.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/VoWMicSetting_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VoWMicSetting_ParamUnitDesc.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/VoWVoiceCommand_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VoWVoiceCommand_AudioParam.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/VoWVoiceCommand_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VoWVoiceCommand_ParamUnitDesc.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/VolumeGainMapUL_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VolumeGainMapUL_AudioParam.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/VolumeGainMapUL_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VolumeGainMapUL_ParamUnitDesc.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/VolumeGainMap_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VolumeGainMap_AudioParam.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/VolumeGainMap_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/VolumeGainMap_ParamUnitDesc.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/Volume_AudioParam.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/Volume_AudioParam.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/audio_param/Volume_ParamUnitDesc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_param/Volume_ParamUnitDesc.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/aurisys_config/CMCC/aurisys_config.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/aurisys_config/CMCC/aurisys_config.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/aurisys_config/CT/aurisys_config.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/aurisys_config/CT/aurisys_config.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/aurisys_config/CTA/aurisys_config.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/aurisys_config/CTA/aurisys_config.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/aurisys_config/CU/aurisys_config.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/aurisys_config/CU/aurisys_config.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/aurisys_config/aurisys_config.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/aurisys_config/aurisys_config.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/aurisys_config_hifi3/aurisys_config_hifi3.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/aurisys_config_hifi3/aurisys_config_hifi3.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/awinic/AW_DSP.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/awinic/AW_DSP.bin \
    vendor/realme/nashc/proprietary/odm/etc/audio/oplus_audio_features.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/oplus_audio_features.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/test_path/common/mixer_paths.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/test_path/common/mixer_paths.xml \
    vendor/realme/nashc/proprietary/odm/etc/audio/test_path/mixer_paths.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/test_path/mixer_paths.xml \
    vendor/realme/nashc/proprietary/odm/etc/camera/CameraHWConfiguration.config:$(TARGET_COPY_OUT_ODM)/etc/camera/CameraHWConfiguration.config \
    vendor/realme/nashc/proprietary/odm/etc/camera/anc_cl_kernel.cache:$(TARGET_COPY_OUT_ODM)/etc/camera/anc_cl_kernel.cache \
    vendor/realme/nashc/proprietary/odm/etc/camera/fb_default:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_default \
    vendor/realme/nashc/proprietary/odm/etc/camera/fwk_config.json:$(TARGET_COPY_OUT_ODM)/etc/camera/fwk_config.json \
    vendor/realme/nashc/proprietary/odm/etc/camera/tonemap/curve_lut_0:$(TARGET_COPY_OUT_ODM)/etc/camera/tonemap/curve_lut_0 \
    vendor/realme/nashc/proprietary/odm/etc/camera/tonemap/curve_lut_1:$(TARGET_COPY_OUT_ODM)/etc/camera/tonemap/curve_lut_1 \
    vendor/realme/nashc/proprietary/odm/etc/camera/tonemap/curve_lut_10:$(TARGET_COPY_OUT_ODM)/etc/camera/tonemap/curve_lut_10 \
    vendor/realme/nashc/proprietary/odm/etc/camera/tonemap/curve_lut_2:$(TARGET_COPY_OUT_ODM)/etc/camera/tonemap/curve_lut_2 \
    vendor/realme/nashc/proprietary/odm/etc/camera/tonemap/curve_lut_3:$(TARGET_COPY_OUT_ODM)/etc/camera/tonemap/curve_lut_3 \
    vendor/realme/nashc/proprietary/odm/etc/camera/tonemap/curve_lut_4:$(TARGET_COPY_OUT_ODM)/etc/camera/tonemap/curve_lut_4 \
    vendor/realme/nashc/proprietary/odm/etc/camera/tonemap/curve_lut_5:$(TARGET_COPY_OUT_ODM)/etc/camera/tonemap/curve_lut_5 \
    vendor/realme/nashc/proprietary/odm/etc/camera/tonemap/curve_lut_6:$(TARGET_COPY_OUT_ODM)/etc/camera/tonemap/curve_lut_6 \
    vendor/realme/nashc/proprietary/odm/etc/camera/tonemap/curve_lut_7:$(TARGET_COPY_OUT_ODM)/etc/camera/tonemap/curve_lut_7 \
    vendor/realme/nashc/proprietary/odm/etc/camera/tonemap/curve_lut_8:$(TARGET_COPY_OUT_ODM)/etc/camera/tonemap/curve_lut_8 \
    vendor/realme/nashc/proprietary/odm/etc/camera/tonemap/curve_lut_9:$(TARGET_COPY_OUT_ODM)/etc/camera/tonemap/curve_lut_9 \
    vendor/realme/nashc/proprietary/odm/etc/camera/tonemap/list.txt:$(TARGET_COPY_OUT_ODM)/etc/camera/tonemap/list.txt \
    vendor/realme/nashc/proprietary/odm/etc/camera/tonemap/s_curve_lut:$(TARGET_COPY_OUT_ODM)/etc/camera/tonemap/s_curve_lut \
    vendor/realme/nashc/proprietary/odm/etc/camera/tonemap/tonemap/curve_lut_0:$(TARGET_COPY_OUT_ODM)/etc/camera/tonemap/tonemap/curve_lut_0 \
    vendor/realme/nashc/proprietary/odm/etc/camera/tonemap/tonemap/curve_lut_1:$(TARGET_COPY_OUT_ODM)/etc/camera/tonemap/tonemap/curve_lut_1 \
    vendor/realme/nashc/proprietary/odm/etc/camera/tonemap/tonemap/curve_lut_10:$(TARGET_COPY_OUT_ODM)/etc/camera/tonemap/tonemap/curve_lut_10 \
    vendor/realme/nashc/proprietary/odm/etc/camera/tonemap/tonemap/curve_lut_2:$(TARGET_COPY_OUT_ODM)/etc/camera/tonemap/tonemap/curve_lut_2 \
    vendor/realme/nashc/proprietary/odm/etc/camera/tonemap/tonemap/curve_lut_3:$(TARGET_COPY_OUT_ODM)/etc/camera/tonemap/tonemap/curve_lut_3 \
    vendor/realme/nashc/proprietary/odm/etc/camera/tonemap/tonemap/curve_lut_4:$(TARGET_COPY_OUT_ODM)/etc/camera/tonemap/tonemap/curve_lut_4 \
    vendor/realme/nashc/proprietary/odm/etc/camera/tonemap/tonemap/curve_lut_5:$(TARGET_COPY_OUT_ODM)/etc/camera/tonemap/tonemap/curve_lut_5 \
    vendor/realme/nashc/proprietary/odm/etc/camera/tonemap/tonemap/curve_lut_6:$(TARGET_COPY_OUT_ODM)/etc/camera/tonemap/tonemap/curve_lut_6 \
    vendor/realme/nashc/proprietary/odm/etc/camera/tonemap/tonemap/curve_lut_7:$(TARGET_COPY_OUT_ODM)/etc/camera/tonemap/tonemap/curve_lut_7 \
    vendor/realme/nashc/proprietary/odm/etc/camera/tonemap/tonemap/curve_lut_8:$(TARGET_COPY_OUT_ODM)/etc/camera/tonemap/tonemap/curve_lut_8 \
    vendor/realme/nashc/proprietary/odm/etc/camera/tonemap/tonemap/curve_lut_9:$(TARGET_COPY_OUT_ODM)/etc/camera/tonemap/tonemap/curve_lut_9 \
    vendor/realme/nashc/proprietary/odm/etc/camera/tonemap/tonemap/list.txt:$(TARGET_COPY_OUT_ODM)/etc/camera/tonemap/tonemap/list.txt \
    vendor/realme/nashc/proprietary/odm/etc/camera/tonemap/tonemap/s_curve_lut:$(TARGET_COPY_OUT_ODM)/etc/camera/tonemap/tonemap/s_curve_lut \
    vendor/realme/nashc/proprietary/odm/etc/camera/tonemap/tonemap/tonemap_lut_0:$(TARGET_COPY_OUT_ODM)/etc/camera/tonemap/tonemap/tonemap_lut_0 \
    vendor/realme/nashc/proprietary/odm/etc/camera/tonemap/tonemap/tonemap_lut_1:$(TARGET_COPY_OUT_ODM)/etc/camera/tonemap/tonemap/tonemap_lut_1 \
    vendor/realme/nashc/proprietary/odm/etc/camera/tonemap/tonemap/tonemap_lut_10:$(TARGET_COPY_OUT_ODM)/etc/camera/tonemap/tonemap/tonemap_lut_10 \
    vendor/realme/nashc/proprietary/odm/etc/camera/tonemap/tonemap/tonemap_lut_2:$(TARGET_COPY_OUT_ODM)/etc/camera/tonemap/tonemap/tonemap_lut_2 \
    vendor/realme/nashc/proprietary/odm/etc/camera/tonemap/tonemap/tonemap_lut_3:$(TARGET_COPY_OUT_ODM)/etc/camera/tonemap/tonemap/tonemap_lut_3 \
    vendor/realme/nashc/proprietary/odm/etc/camera/tonemap/tonemap/tonemap_lut_4:$(TARGET_COPY_OUT_ODM)/etc/camera/tonemap/tonemap/tonemap_lut_4 \
    vendor/realme/nashc/proprietary/odm/etc/camera/tonemap/tonemap/tonemap_lut_5:$(TARGET_COPY_OUT_ODM)/etc/camera/tonemap/tonemap/tonemap_lut_5 \
    vendor/realme/nashc/proprietary/odm/etc/camera/tonemap/tonemap/tonemap_lut_6:$(TARGET_COPY_OUT_ODM)/etc/camera/tonemap/tonemap/tonemap_lut_6 \
    vendor/realme/nashc/proprietary/odm/etc/camera/tonemap/tonemap/tonemap_lut_7:$(TARGET_COPY_OUT_ODM)/etc/camera/tonemap/tonemap/tonemap_lut_7 \
    vendor/realme/nashc/proprietary/odm/etc/camera/tonemap/tonemap/tonemap_lut_8:$(TARGET_COPY_OUT_ODM)/etc/camera/tonemap/tonemap/tonemap_lut_8 \
    vendor/realme/nashc/proprietary/odm/etc/camera/tonemap/tonemap/tonemap_lut_9:$(TARGET_COPY_OUT_ODM)/etc/camera/tonemap/tonemap/tonemap_lut_9 \
    vendor/realme/nashc/proprietary/odm/etc/camera/tonemap/tonemap_lut_0:$(TARGET_COPY_OUT_ODM)/etc/camera/tonemap/tonemap_lut_0 \
    vendor/realme/nashc/proprietary/odm/etc/camera/tonemap/tonemap_lut_1:$(TARGET_COPY_OUT_ODM)/etc/camera/tonemap/tonemap_lut_1 \
    vendor/realme/nashc/proprietary/odm/etc/camera/tonemap/tonemap_lut_10:$(TARGET_COPY_OUT_ODM)/etc/camera/tonemap/tonemap_lut_10 \
    vendor/realme/nashc/proprietary/odm/etc/camera/tonemap/tonemap_lut_2:$(TARGET_COPY_OUT_ODM)/etc/camera/tonemap/tonemap_lut_2 \
    vendor/realme/nashc/proprietary/odm/etc/camera/tonemap/tonemap_lut_3:$(TARGET_COPY_OUT_ODM)/etc/camera/tonemap/tonemap_lut_3 \
    vendor/realme/nashc/proprietary/odm/etc/camera/tonemap/tonemap_lut_4:$(TARGET_COPY_OUT_ODM)/etc/camera/tonemap/tonemap_lut_4 \
    vendor/realme/nashc/proprietary/odm/etc/camera/tonemap/tonemap_lut_5:$(TARGET_COPY_OUT_ODM)/etc/camera/tonemap/tonemap_lut_5 \
    vendor/realme/nashc/proprietary/odm/etc/camera/tonemap/tonemap_lut_6:$(TARGET_COPY_OUT_ODM)/etc/camera/tonemap/tonemap_lut_6 \
    vendor/realme/nashc/proprietary/odm/etc/camera/tonemap/tonemap_lut_7:$(TARGET_COPY_OUT_ODM)/etc/camera/tonemap/tonemap_lut_7 \
    vendor/realme/nashc/proprietary/odm/etc/camera/tonemap/tonemap_lut_8:$(TARGET_COPY_OUT_ODM)/etc/camera/tonemap/tonemap_lut_8 \
    vendor/realme/nashc/proprietary/odm/etc/camera/tonemap/tonemap_lut_9:$(TARGET_COPY_OUT_ODM)/etc/camera/tonemap/tonemap_lut_9 \
    vendor/realme/nashc/proprietary/odm/etc/init/init.pn8x.nfc.rc:$(TARGET_COPY_OUT_ODM)/etc/init/init.pn8x.nfc.rc \
    vendor/realme/nashc/proprietary/odm/etc/init/vendor.oplus.hardware.biometrics.fingerprint@2.1-service.rc:$(TARGET_COPY_OUT_ODM)/etc/init/vendor.oplus.hardware.biometrics.fingerprint@2.1-service.rc \
    vendor/realme/nashc/proprietary/odm/etc/init/vendor.oplus.hardware.charger@1.0-service.rc:$(TARGET_COPY_OUT_ODM)/etc/init/vendor.oplus.hardware.charger@1.0-service.rc \
    vendor/realme/nashc/proprietary/odm/etc/init/vendor.oplus.hardware.oplusSensor@1.0-service.rc:$(TARGET_COPY_OUT_ODM)/etc/init/vendor.oplus.hardware.oplusSensor@1.0-service.rc \
    vendor/realme/nashc/proprietary/odm/etc/sensor/sensor_config.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/sensor_config.json \
    vendor/realme/nashc/proprietary/odm/firmware/aw88264/aw882xx_rcv_reg.bin:$(TARGET_COPY_OUT_ODM)/firmware/aw88264/aw882xx_rcv_reg.bin \
    vendor/realme/nashc/proprietary/odm/firmware/aw88264/aw882xx_spk_reg.bin:$(TARGET_COPY_OUT_ODM)/firmware/aw88264/aw882xx_spk_reg.bin \
    vendor/realme/nashc/proprietary/odm/firmware/fastchg/charging_thermal_config_default.txt:$(TARGET_COPY_OUT_ODM)/firmware/fastchg/charging_thermal_config_default.txt \
    vendor/realme/nashc/proprietary/odm/firmware/tp/20730/FW_FT3518_SAMSUNG.img:$(TARGET_COPY_OUT_ODM)/firmware/tp/20730/FW_FT3518_SAMSUNG.img \
    vendor/realme/nashc/proprietary/odm/firmware/tp/20730/FW_FT3518_SAMSUNG_FAE.img:$(TARGET_COPY_OUT_ODM)/firmware/tp/20730/FW_FT3518_SAMSUNG_FAE.img \
    vendor/realme/nashc/proprietary/odm/firmware/tp/20730/FW_GT9886_SAMSUNG.img:$(TARGET_COPY_OUT_ODM)/firmware/tp/20730/FW_GT9886_SAMSUNG.img \
    vendor/realme/nashc/proprietary/odm/firmware/tp/20730/FW_GT9886_SAMSUNG_FAE.img:$(TARGET_COPY_OUT_ODM)/firmware/tp/20730/FW_GT9886_SAMSUNG_FAE.img \
    vendor/realme/nashc/proprietary/odm/firmware/tp/20730/LIMIT_FT3518_SAMSUNG.img:$(TARGET_COPY_OUT_ODM)/firmware/tp/20730/LIMIT_FT3518_SAMSUNG.img \
    vendor/realme/nashc/proprietary/odm/firmware/tp/20730/LIMIT_GT9886_SAMSUNG.img:$(TARGET_COPY_OUT_ODM)/firmware/tp/20730/LIMIT_GT9886_SAMSUNG.img \
    vendor/realme/nashc/proprietary/odm/vendor/app/mcRegistry/03020000000000000000000000000000.tabin:$(TARGET_COPY_OUT_ODM)/vendor/app/mcRegistry/03020000000000000000000000000000.tabin \
    vendor/realme/nashc/proprietary/odm/vendor/app/mcRegistry/030c0000000000000000000000000000.drbin:$(TARGET_COPY_OUT_ODM)/vendor/app/mcRegistry/030c0000000000000000000000000000.drbin \
    vendor/realme/nashc/proprietary/odm/vendor/app/mcRegistry/030c0000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_ODM)/vendor/app/mcRegistry/030c0000000000000000000000000000.tlbin \
    vendor/realme/nashc/proprietary/odm/vendor/app/mcRegistry/04320000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_ODM)/vendor/app/mcRegistry/04320000000000000000000000000000.tlbin \
    vendor/realme/nashc/proprietary/odm/vendor/app/mcRegistry/05060000000000000000000000000000.tabin:$(TARGET_COPY_OUT_ODM)/vendor/app/mcRegistry/05060000000000000000000000000000.tabin \
    vendor/realme/nashc/proprietary/odm/vendor/app/mcRegistry/05070000000000000000000000000000.drbin:$(TARGET_COPY_OUT_ODM)/vendor/app/mcRegistry/05070000000000000000000000000000.drbin \
    vendor/realme/nashc/proprietary/odm/vendor/app/mcRegistry/070f0000000000000000000000000a0a.tlbin:$(TARGET_COPY_OUT_ODM)/vendor/app/mcRegistry/070f0000000000000000000000000a0a.tlbin \
    vendor/realme/nashc/proprietary/odm/vendor/app/mcRegistry/08010203000000000000000000000000.tabin:$(TARGET_COPY_OUT_ODM)/vendor/app/mcRegistry/08010203000000000000000000000000.tabin \
    vendor/realme/nashc/proprietary/odm/vendor/app/mcRegistry/09060000000000000000000000000000.tabin:$(TARGET_COPY_OUT_ODM)/vendor/app/mcRegistry/09060000000000000000000000000000.tabin \
    vendor/realme/nashc/proprietary/odm/vendor/app/mcRegistry/09070000000000000000000000000000.drbin:$(TARGET_COPY_OUT_ODM)/vendor/app/mcRegistry/09070000000000000000000000000000.drbin \
    vendor/realme/nashc/proprietary/odm/vendor/app/mcRegistry/09080000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_ODM)/vendor/app/mcRegistry/09080000000000000000000000000000.tlbin \
    vendor/realme/nashc/proprietary/system_ext/etc/init/init.vtservice.rc:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/init/init.vtservice.rc \
    vendor/realme/nashc/proprietary/vendor/app/mcRegistry/020b0000000000000000000000000000.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/020b0000000000000000000000000000.drbin \
    vendor/realme/nashc/proprietary/vendor/app/mcRegistry/020b0000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/020b0000000000000000000000000000.tlbin \
    vendor/realme/nashc/proprietary/vendor/app/mcRegistry/020f0000000000000000000000000000.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/020f0000000000000000000000000000.drbin \
    vendor/realme/nashc/proprietary/vendor/app/mcRegistry/020f0000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/020f0000000000000000000000000000.tlbin \
    vendor/realme/nashc/proprietary/vendor/app/mcRegistry/030c0000000000000000000000000000.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/030c0000000000000000000000000000.drbin \
    vendor/realme/nashc/proprietary/vendor/app/mcRegistry/030c0000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/030c0000000000000000000000000000.tlbin \
    vendor/realme/nashc/proprietary/vendor/app/mcRegistry/05120000000000000000000000000000.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/05120000000000000000000000000000.drbin \
    vendor/realme/nashc/proprietary/vendor/app/mcRegistry/05120000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/05120000000000000000000000000000.tlbin \
    vendor/realme/nashc/proprietary/vendor/app/mcRegistry/05120000000000000000000000000001.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/05120000000000000000000000000001.drbin \
    vendor/realme/nashc/proprietary/vendor/app/mcRegistry/05120000000000000000000000000001.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/05120000000000000000000000000001.tlbin \
    vendor/realme/nashc/proprietary/vendor/app/mcRegistry/06090000000000000000000000000000.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/06090000000000000000000000000000.drbin \
    vendor/realme/nashc/proprietary/vendor/app/mcRegistry/06090000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/06090000000000000000000000000000.tlbin \
    vendor/realme/nashc/proprietary/vendor/app/mcRegistry/0706000000000000000000000000004d.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/0706000000000000000000000000004d.tlbin \
    vendor/realme/nashc/proprietary/vendor/app/mcRegistry/07060000000000000000000000007169.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/07060000000000000000000000007169.drbin \
    vendor/realme/nashc/proprietary/vendor/app/mcRegistry/07060000000000000000000000007169.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/07060000000000000000000000007169.tlbin \
    vendor/realme/nashc/proprietary/vendor/app/mcRegistry/07061000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/07061000000000000000000000000000.tlbin \
    vendor/realme/nashc/proprietary/vendor/app/mcRegistry/07150000000000000000000000000000.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/07150000000000000000000000000000.drbin \
    vendor/realme/nashc/proprietary/vendor/app/mcRegistry/07150000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/07150000000000000000000000000000.tlbin \
    vendor/realme/nashc/proprietary/vendor/app/mcRegistry/07170000000000000000000000000000.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/07170000000000000000000000000000.drbin \
    vendor/realme/nashc/proprietary/vendor/app/mcRegistry/07170000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/07170000000000000000000000000000.tlbin \
    vendor/realme/nashc/proprietary/vendor/app/mcRegistry/08020000000000000000000000007169.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/08020000000000000000000000007169.tabin \
    vendor/realme/nashc/proprietary/vendor/app/mcRegistry/08030000000000000000000000000000.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/08030000000000000000000000000000.tabin \
    vendor/realme/nashc/proprietary/vendor/app/mcRegistry/08040000000000000000000000003419.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/08040000000000000000000000003419.tabin \
    vendor/realme/nashc/proprietary/vendor/app/mcRegistry/08050000000000000000000000003419.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/08050000000000000000000000003419.drbin \
    vendor/realme/nashc/proprietary/vendor/app/mcRegistry/08050000000000000000000000003419.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/08050000000000000000000000003419.tlbin \
    vendor/realme/nashc/proprietary/vendor/app/mcRegistry/08070000000000000000000000008270.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/08070000000000000000000000008270.drbin \
    vendor/realme/nashc/proprietary/vendor/app/mcRegistry/08070000000000000000000000008270.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/08070000000000000000000000008270.tlbin \
    vendor/realme/nashc/proprietary/vendor/app/mcRegistry/08110000000000000000000000000000.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/08110000000000000000000000000000.tabin \
    vendor/realme/nashc/proprietary/vendor/app/mcRegistry/09010000000000000000000000000000.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/09010000000000000000000000000000.tabin \
    vendor/realme/nashc/proprietary/vendor/app/mcRegistry/09030000000000000000000000008270.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/09030000000000000000000000008270.tabin \
    vendor/realme/nashc/proprietary/vendor/app/mcRegistry/09190000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/09190000000000000000000000000000.tlbin \
    vendor/realme/nashc/proprietary/vendor/app/mcRegistry/40188311faf343488db888ad39496f9a.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/40188311faf343488db888ad39496f9a.drbin \
    vendor/realme/nashc/proprietary/vendor/app/mcRegistry/40188311faf343488db888ad39496f9a.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/40188311faf343488db888ad39496f9a.tlbin \
    vendor/realme/nashc/proprietary/vendor/app/mcRegistry/5020170115e016302017012521300000.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/5020170115e016302017012521300000.drbin \
    vendor/realme/nashc/proprietary/vendor/app/mcRegistry/5020170115e016302017012521300000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/5020170115e016302017012521300000.tlbin \
    vendor/realme/nashc/proprietary/vendor/app/mcRegistry/9073f03a9618383bb1856eb3f990babd.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/9073f03a9618383bb1856eb3f990babd.drbin \
    vendor/realme/nashc/proprietary/vendor/app/mcRegistry/9073f03a9618383bb1856eb3f990babd.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/9073f03a9618383bb1856eb3f990babd.tlbin \
    vendor/realme/nashc/proprietary/vendor/app/mcRegistry/98fb95bcb4bf42d26473eae48690d7ea.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/98fb95bcb4bf42d26473eae48690d7ea.tabin \
    vendor/realme/nashc/proprietary/vendor/app/mcRegistry/e97c270ea5c44c58bcd3384a2fa2539e.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/e97c270ea5c44c58bcd3384a2fa2539e.tabin \
    vendor/realme/nashc/proprietary/vendor/etc/.tp/.ht120.mtc:$(TARGET_COPY_OUT_VENDOR)/etc/.tp/.ht120.mtc \
    vendor/realme/nashc/proprietary/vendor/etc/.tp/.thermal_policy_08:$(TARGET_COPY_OUT_VENDOR)/etc/.tp/.thermal_policy_08 \
    vendor/realme/nashc/proprietary/vendor/etc/.tp/thermal.conf:$(TARGET_COPY_OUT_VENDOR)/etc/.tp/thermal.conf \
    vendor/realme/nashc/proprietary/vendor/etc/.tp/thermal.off.conf:$(TARGET_COPY_OUT_VENDOR)/etc/.tp/thermal.off.conf \
    vendor/realme/nashc/proprietary/vendor/etc/ecc_list.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list.xml \
    vendor/realme/nashc/proprietary/vendor/etc/ecc_list_OP01.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP01.xml \
    vendor/realme/nashc/proprietary/vendor/etc/ecc_list_OP02.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP02.xml \
    vendor/realme/nashc/proprietary/vendor/etc/ecc_list_OP09.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP09.xml \
    vendor/realme/nashc/proprietary/vendor/etc/ecc_list_OP12.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP12.xml \
    vendor/realme/nashc/proprietary/vendor/etc/ecc_list_OP17.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP17.xml \
    vendor/realme/nashc/proprietary/vendor/etc/ecc_list_OP18.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP18.xml \
    vendor/realme/nashc/proprietary/vendor/etc/ecc_list_OP20.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP20.xml \
    vendor/realme/nashc/proprietary/vendor/etc/ecc_list_OP236.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP236.xml \
    vendor/realme/nashc/proprietary/vendor/etc/ecc_list_preference.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_preference.xml \
    vendor/realme/nashc/proprietary/vendor/etc/gnss/agps_profiles_conf2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/agps_profiles_conf2.xml \
    vendor/realme/nashc/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_ATnT_Mexico.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_ATnT_Mexico.xml \
    vendor/realme/nashc/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_ATnT_US.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_ATnT_US.xml \
    vendor/realme/nashc/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_CT.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_CT.xml \
    vendor/realme/nashc/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Claro_Peru.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Claro_Peru.xml \
    vendor/realme/nashc/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Entel_Peru.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Entel_Peru.xml \
    vendor/realme/nashc/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_KDDI.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_KDDI.xml \
    vendor/realme/nashc/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_QXWZ.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_QXWZ.xml \
    vendor/realme/nashc/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Rakuten.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Rakuten.xml \
    vendor/realme/nashc/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_SK_Telecom.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_SK_Telecom.xml \
    vendor/realme/nashc/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_SoftBank.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_SoftBank.xml \
    vendor/realme/nashc/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Sprint.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Sprint.xml \
    vendor/realme/nashc/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_T-Mobile_US.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_T-Mobile_US.xml \
    vendor/realme/nashc/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Test_SIM1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Test_SIM1.xml \
    vendor/realme/nashc/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Test_SIM2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Test_SIM2.xml \
    vendor/realme/nashc/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Verizon_Wireless.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Verizon_Wireless.xml \
    vendor/realme/nashc/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Vodafone.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Vodafone.xml \
    vendor/realme/nashc/proprietary/vendor/etc/init/android.hardware.bluetooth@1.1-service-mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.bluetooth@1.1-service-mediatek.rc \
    vendor/realme/nashc/proprietary/vendor/etc/init/android.hardware.drm@1.4-service.widevine.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.drm@1.4-service.widevine.rc \
    vendor/realme/nashc/proprietary/vendor/etc/init/android.hardware.gnss-service.mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gnss-service.mediatek.rc \
    vendor/realme/nashc/proprietary/vendor/etc/init/android.hardware.graphics.allocator@4.0-service-mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.graphics.allocator@4.0-service-mediatek.rc \
    vendor/realme/nashc/proprietary/vendor/etc/init/android.hardware.keymaster@4.0-service.trustonic.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.keymaster@4.0-service.trustonic.rc \
    vendor/realme/nashc/proprietary/vendor/etc/init/android.hardware.media.c2@1.2-mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.media.c2@1.2-mediatek.rc \
    vendor/realme/nashc/proprietary/vendor/etc/init/android.hardware.neuralnetworks@1.3-service-mtk-neuron.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.neuralnetworks@1.3-service-mtk-neuron.rc \
    vendor/realme/nashc/proprietary/vendor/etc/init/android.hardware.secure_element@1.2-service-mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.secure_element@1.2-service-mediatek.rc \
    vendor/realme/nashc/proprietary/vendor/etc/init/camerahalserver.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/camerahalserver.rc \
    vendor/realme/nashc/proprietary/vendor/etc/init/gsm0710muxd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/gsm0710muxd.rc \
    vendor/realme/nashc/proprietary/vendor/etc/init/init.cccimdinit.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.cccimdinit.rc \
    vendor/realme/nashc/proprietary/vendor/etc/init/init.cccirpcd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.cccirpcd.rc \
    vendor/realme/nashc/proprietary/vendor/etc/init/init.thermal.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.thermal.rc \
    vendor/realme/nashc/proprietary/vendor/etc/init/init.thermal_manager.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.thermal_manager.rc \
    vendor/realme/nashc/proprietary/vendor/etc/init/init.volte_imcb.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.volte_imcb.rc \
    vendor/realme/nashc/proprietary/vendor/etc/init/init.volte_imsm_93.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.volte_imsm_93.rc \
    vendor/realme/nashc/proprietary/vendor/etc/init/init.volte_md_status.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.volte_md_status.rc \
    vendor/realme/nashc/proprietary/vendor/etc/init/init.volte_stack.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.volte_stack.rc \
    vendor/realme/nashc/proprietary/vendor/etc/init/init.volte_ua.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.volte_ua.rc \
    vendor/realme/nashc/proprietary/vendor/etc/init/init.vtservice_hidl.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.vtservice_hidl.rc \
    vendor/realme/nashc/proprietary/vendor/etc/init/mtk_agpsd_p.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/mtk_agpsd_p.rc \
    vendor/realme/nashc/proprietary/vendor/etc/init/mtkrild.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/mtkrild.rc \
    vendor/realme/nashc/proprietary/vendor/etc/init/muxreport.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/muxreport.rc \
    vendor/realme/nashc/proprietary/vendor/etc/init/netdagent.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/netdagent.rc \
    vendor/realme/nashc/proprietary/vendor/etc/init/nvram_daemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/nvram_daemon.rc \
    vendor/realme/nashc/proprietary/vendor/etc/init/tee.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/tee.rc \
    vendor/realme/nashc/proprietary/vendor/etc/init/tetheroffloadservice.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/tetheroffloadservice.rc \
    vendor/realme/nashc/proprietary/vendor/etc/init/trustonic.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/trustonic.rc \
    vendor/realme/nashc/proprietary/vendor/etc/init/vendor.mediatek.hardware.mms@1.6-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.mms@1.6-service.rc \
    vendor/realme/nashc/proprietary/vendor/etc/init/vendor.mediatek.hardware.nvram@1.1-sevice.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.nvram@1.1-sevice.rc \
    vendor/realme/nashc/proprietary/vendor/etc/init/vendor.mediatek.hardware.pq@2.2-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.pq@2.2-service.rc \
    vendor/realme/nashc/proprietary/vendor/etc/init/volte_clientapi_ua.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/volte_clientapi_ua.rc \
    vendor/realme/nashc/proprietary/vendor/etc/init/vpud.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vpud.rc \
    vendor/realme/nashc/proprietary/vendor/etc/libnfc-nci.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nci.conf \
    vendor/realme/nashc/proprietary/vendor/etc/libnfc-nxp.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nxp.conf \
    vendor/realme/nashc/proprietary/vendor/etc/slp_conf:$(TARGET_COPY_OUT_VENDOR)/etc/slp_conf \
    vendor/realme/nashc/proprietary/vendor/etc/special_pws_channel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/special_pws_channel.xml \
    vendor/realme/nashc/proprietary/vendor/etc/vendor-apns-conf.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vendor-apns-conf.xml \
    vendor/realme/nashc/proprietary/vendor/etc/virtual-spn-conf-by-efgid1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/virtual-spn-conf-by-efgid1.xml \
    vendor/realme/nashc/proprietary/vendor/etc/virtual-spn-conf-by-efpnn.xml:$(TARGET_COPY_OUT_VENDOR)/etc/virtual-spn-conf-by-efpnn.xml \
    vendor/realme/nashc/proprietary/vendor/etc/virtual-spn-conf-by-efspn.xml:$(TARGET_COPY_OUT_VENDOR)/etc/virtual-spn-conf-by-efspn.xml \
    vendor/realme/nashc/proprietary/vendor/etc/virtual-spn-conf-by-imsi.xml:$(TARGET_COPY_OUT_VENDOR)/etc/virtual-spn-conf-by-imsi.xml \
    vendor/realme/nashc/proprietary/vendor/firmware/BT_FW.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/BT_FW.cfg \
    vendor/realme/nashc/proprietary/vendor/firmware/WIFI_RAM_CODE_soc1_0_2a_1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/WIFI_RAM_CODE_soc1_0_2a_1.bin \
    vendor/realme/nashc/proprietary/vendor/firmware/WMT_SOC.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/WMT_SOC.cfg \
    vendor/realme/nashc/proprietary/vendor/firmware/lib3a.ccu:$(TARGET_COPY_OUT_VENDOR)/firmware/lib3a.ccu \
    vendor/realme/nashc/proprietary/vendor/firmware/libccu_gc02m1_mipi_raw_207301:$(TARGET_COPY_OUT_VENDOR)/firmware/libccu_gc02m1_mipi_raw_207301 \
    vendor/realme/nashc/proprietary/vendor/firmware/libccu_gc02m1_mipi_raw_207302:$(TARGET_COPY_OUT_VENDOR)/firmware/libccu_gc02m1_mipi_raw_207302 \
    vendor/realme/nashc/proprietary/vendor/firmware/libccu_gc02m1b_mipi_mono_207301:$(TARGET_COPY_OUT_VENDOR)/firmware/libccu_gc02m1b_mipi_mono_207301 \
    vendor/realme/nashc/proprietary/vendor/firmware/libccu_gc02m1b_mipi_mono_207302:$(TARGET_COPY_OUT_VENDOR)/firmware/libccu_gc02m1b_mipi_mono_207302 \
    vendor/realme/nashc/proprietary/vendor/firmware/libccu_imx350_mipi_raw1:$(TARGET_COPY_OUT_VENDOR)/firmware/libccu_imx350_mipi_raw1 \
    vendor/realme/nashc/proprietary/vendor/firmware/libccu_imx350_mipi_raw2:$(TARGET_COPY_OUT_VENDOR)/firmware/libccu_imx350_mipi_raw2 \
    vendor/realme/nashc/proprietary/vendor/firmware/libccu_imx386_mipi_mono1:$(TARGET_COPY_OUT_VENDOR)/firmware/libccu_imx386_mipi_mono1 \
    vendor/realme/nashc/proprietary/vendor/firmware/libccu_imx386_mipi_mono2:$(TARGET_COPY_OUT_VENDOR)/firmware/libccu_imx386_mipi_mono2 \
    vendor/realme/nashc/proprietary/vendor/firmware/libccu_imx386_mipi_raw1:$(TARGET_COPY_OUT_VENDOR)/firmware/libccu_imx386_mipi_raw1 \
    vendor/realme/nashc/proprietary/vendor/firmware/libccu_imx386_mipi_raw2:$(TARGET_COPY_OUT_VENDOR)/firmware/libccu_imx386_mipi_raw2 \
    vendor/realme/nashc/proprietary/vendor/firmware/libccu_imx398_mipi_raw1:$(TARGET_COPY_OUT_VENDOR)/firmware/libccu_imx398_mipi_raw1 \
    vendor/realme/nashc/proprietary/vendor/firmware/libccu_imx398_mipi_raw2:$(TARGET_COPY_OUT_VENDOR)/firmware/libccu_imx398_mipi_raw2 \
    vendor/realme/nashc/proprietary/vendor/firmware/libccu_imx471_mipi_raw2_207301:$(TARGET_COPY_OUT_VENDOR)/firmware/libccu_imx471_mipi_raw2_207301 \
    vendor/realme/nashc/proprietary/vendor/firmware/libccu_imx471_mipi_raw2_207302:$(TARGET_COPY_OUT_VENDOR)/firmware/libccu_imx471_mipi_raw2_207302 \
    vendor/realme/nashc/proprietary/vendor/firmware/libccu_imx499_mipi_raw1:$(TARGET_COPY_OUT_VENDOR)/firmware/libccu_imx499_mipi_raw1 \
    vendor/realme/nashc/proprietary/vendor/firmware/libccu_imx499_mipi_raw2:$(TARGET_COPY_OUT_VENDOR)/firmware/libccu_imx499_mipi_raw2 \
    vendor/realme/nashc/proprietary/vendor/firmware/libccu_imx519_mipi_raw1:$(TARGET_COPY_OUT_VENDOR)/firmware/libccu_imx519_mipi_raw1 \
    vendor/realme/nashc/proprietary/vendor/firmware/libccu_imx519_mipi_raw2:$(TARGET_COPY_OUT_VENDOR)/firmware/libccu_imx519_mipi_raw2 \
    vendor/realme/nashc/proprietary/vendor/firmware/libccu_imx576_mipi_raw1:$(TARGET_COPY_OUT_VENDOR)/firmware/libccu_imx576_mipi_raw1 \
    vendor/realme/nashc/proprietary/vendor/firmware/libccu_imx576_mipi_raw2:$(TARGET_COPY_OUT_VENDOR)/firmware/libccu_imx576_mipi_raw2 \
    vendor/realme/nashc/proprietary/vendor/firmware/libccu_imx586_mipi_raw1:$(TARGET_COPY_OUT_VENDOR)/firmware/libccu_imx586_mipi_raw1 \
    vendor/realme/nashc/proprietary/vendor/firmware/libccu_imx586_mipi_raw2:$(TARGET_COPY_OUT_VENDOR)/firmware/libccu_imx586_mipi_raw2 \
    vendor/realme/nashc/proprietary/vendor/firmware/libccu_ov64b_mipi_raw_207301:$(TARGET_COPY_OUT_VENDOR)/firmware/libccu_ov64b_mipi_raw_207301 \
    vendor/realme/nashc/proprietary/vendor/firmware/libccu_ov64b_mipi_raw_207302:$(TARGET_COPY_OUT_VENDOR)/firmware/libccu_ov64b_mipi_raw_207302 \
    vendor/realme/nashc/proprietary/vendor/firmware/libccu_ov8856_mipi_raw2_207301:$(TARGET_COPY_OUT_VENDOR)/firmware/libccu_ov8856_mipi_raw2_207301 \
    vendor/realme/nashc/proprietary/vendor/firmware/libccu_ov8856_mipi_raw2_207302:$(TARGET_COPY_OUT_VENDOR)/firmware/libccu_ov8856_mipi_raw2_207302 \
    vendor/realme/nashc/proprietary/vendor/firmware/libccu_s5k2l7_mipi_raw1:$(TARGET_COPY_OUT_VENDOR)/firmware/libccu_s5k2l7_mipi_raw1 \
    vendor/realme/nashc/proprietary/vendor/firmware/libccu_s5k2l7_mipi_raw2:$(TARGET_COPY_OUT_VENDOR)/firmware/libccu_s5k2l7_mipi_raw2 \
    vendor/realme/nashc/proprietary/vendor/firmware/libccu_s5k2lqsx_mipi_raw1:$(TARGET_COPY_OUT_VENDOR)/firmware/libccu_s5k2lqsx_mipi_raw1 \
    vendor/realme/nashc/proprietary/vendor/firmware/libccu_s5k2lqsx_mipi_raw2:$(TARGET_COPY_OUT_VENDOR)/firmware/libccu_s5k2lqsx_mipi_raw2 \
    vendor/realme/nashc/proprietary/vendor/firmware/libccu_s5k2t7sp_mipi_raw1:$(TARGET_COPY_OUT_VENDOR)/firmware/libccu_s5k2t7sp_mipi_raw1 \
    vendor/realme/nashc/proprietary/vendor/firmware/libccu_s5k2t7sp_mipi_raw2:$(TARGET_COPY_OUT_VENDOR)/firmware/libccu_s5k2t7sp_mipi_raw2 \
    vendor/realme/nashc/proprietary/vendor/firmware/libccu_s5k4h7_mipi_raw1:$(TARGET_COPY_OUT_VENDOR)/firmware/libccu_s5k4h7_mipi_raw1 \
    vendor/realme/nashc/proprietary/vendor/firmware/libccu_s5k4h7_mipi_raw2:$(TARGET_COPY_OUT_VENDOR)/firmware/libccu_s5k4h7_mipi_raw2 \
    vendor/realme/nashc/proprietary/vendor/firmware/libccu_s5khm2sp_mipi_raw1:$(TARGET_COPY_OUT_VENDOR)/firmware/libccu_s5khm2sp_mipi_raw1 \
    vendor/realme/nashc/proprietary/vendor/firmware/libccu_s5khm2sp_mipi_raw2:$(TARGET_COPY_OUT_VENDOR)/firmware/libccu_s5khm2sp_mipi_raw2 \
    vendor/realme/nashc/proprietary/vendor/firmware/soc1_0_patch_mcu_2a_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc1_0_patch_mcu_2a_1_hdr.bin \
    vendor/realme/nashc/proprietary/vendor/firmware/soc1_0_ram_bt_2a_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc1_0_ram_bt_2a_1_hdr.bin \
    vendor/realme/nashc/proprietary/vendor/firmware/soc1_0_ram_mcu_2a_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc1_0_ram_mcu_2a_1_hdr.bin \
    vendor/realme/nashc/proprietary/vendor/firmware/soc1_0_ram_wifi_2a_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc1_0_ram_wifi_2a_1_hdr.bin

PRODUCT_PACKAGES += \
    libTEECommon \
    libaedv \
    libbwc \
    libcustom_nvram \
    libfile_op \
    libion_mtk \
    libion_ulit \
    libladder \
    libmtkcutils \
    libmtkproperty \
    libmtkrillog \
    libmtkspparser \
    libnvram \
    libnvram_sec \
    libspeechparser_vendor \
    libverno \
    libvpu \
    libvpu5 \
    libmtk_drvb \
    vendor.mediatek.hardware.nvram@1.0 \
    vendor.mediatek.hardware.nvram@1.1 \
    vendor.mediatek.hardware.videotelephony@1.0_vendor \
    AVCSecureVdecCA \
    VP9SecureVdecCA \
    audio.primary.mt6785 \
    audio.r_submix.mt6785 \
    libHEVCdec_sa.ca7.android \
    libMtkSpeechEnh \
    lib_iir \
    lib_speech_enh \
    libalsautils-v31 \
    libaudio_engineer_test \
    libaudio_param_parser-vnd \
    libaudiocompensationfilter_vendor \
    libaudiocompensationfilterc \
    libaudiocomponentengine_vendor \
    libaudiocomponentenginec \
    libaudiocustparam_vendor \
    libaudiodcrflt_vendor \
    libaudiofmtconv \
    libaudioloudc \
    libaudioprimarydevicehalifclient \
    libaudiotoolkit_vendor \
    libaurisysdemo \
    libbessound_hd_mtk_vendor \
    libblisrc32_vendor \
    libcvsd_mtk \
    libh264dec_customize \
    libh264dec_sa.ca7 \
    libh264dec_sd.ca7 \
    libh264dec_se.ca7 \
    libh264enc_sa.ca7 \
    libhevce_sb.ca7.android \
    libipsec_ims_shr \
    libktvdrc \
    libktveffect \
    libktveffect_rec \
    libktveq \
    libktvns \
    libktvreverb \
    libktvsoundtouch \
    libktvvolume \
    libmp4enc_sa.ca7 \
    libmsbc_mtk \
    libmtklimiter_vendor \
    libmtkshifter_vendor \
    libnxp_extamp_intf \
    liboplus_audio_config \
    librcs_interface \
    librcs_volte_core \
    librt_extamp_intf \
    libspeech_enh_lib \
    libthermalalgo \
    libthha \
    libvcodec_oal \
    libvcodec_utility \
    libvcodecdrv \
    libvcodecdrv_header_stub \
    libvolte_core_shr \
    libvolte_xdmc_shr \
    libvp8dec_sa.ca7 \
    libvp8enc_sa.ca7 \
    libvp9dec_sa.ca7 \
    libvpud_vcodec \
    vendor.mediatek.hardware.audio@7.1 \
    vendor.mediatek.hardware.bluetooth.audio@2.1 \
    vendor.mediatek.hardware.bluetooth.audio@2.2 \
    vendor.mediatek.hardware.rcs@2.0 \
    APUWareUtilsServer \
    arm.graphics-V1-ndk_platform \
    libGLES_mali \
    libGLES_meow \
    libMEOW_data \
    libMEOW_gift \
    libMEOW_qt \
    libMEOW_trace \
    gc02m1_mipi_raw_20730_IdxMgr \
    gc02m1_mipi_raw_20730_tuning \
    gc02m1b_mipi_mono_20730_IdxMgr \
    gc02m1b_mipi_mono_20730_tuning \
    android.hardware.bluetooth@1.1-impl-mediatek \
    android.hardware.camera.provider@2.6-impl-mediatek \
    android.hardware.gnss-impl-mediatek \
    android.hardware.gnss@2.1-impl-mediatek \
    android.hardware.graphics.allocator@4.0-impl-mediatek \
    android.hardware.graphics.mapper@4.0-impl-mediatek \
    gps.default \
    hwcomposer.mt6785 \
    kmsetkey.trustonic \
    libMcGatekeeper \
    sensors.mt6785 \
    sound_trigger.primary.default \
    vendor.mediatek.hardware.camera.atms@1.0-impl \
    vendor.mediatek.hardware.camera.bgservice@1.1-impl \
    vendor.mediatek.hardware.camera.isphal@1.0-impl \
    vendor.mediatek.hardware.camera.lomoeffect@1.0-impl \
    vendor.mediatek.hardware.camera.postproc@1.0-impl \
    vendor.mediatek.hardware.mms@1.6-impl \
    vendor.mediatek.hardware.nvram@1.1-impl \
    vendor.mediatek.hardware.pq@2.15-impl \
    vendor.mediatek.hardware.videotelephony@1.0-impl \
    vendor.oplus.hardware.cameraextension@1.0-service-impl \
    imx350_mipi_raw_IdxMgr \
    imx350_mipi_raw_tuning \
    imx386_mipi_mono_IdxMgr \
    imx386_mipi_mono_tuning \
    imx386_mipi_raw_IdxMgr \
    imx386_mipi_raw_tuning \
    imx398_mipi_raw_IdxMgr \
    imx398_mipi_raw_tuning \
    imx471_mipi_raw2_20730_IdxMgr \
    imx471_mipi_raw2_20730_tuning \
    imx499_mipi_raw_IdxMgr \
    imx499_mipi_raw_tuning \
    imx519_mipi_raw_IdxMgr \
    imx519_mipi_raw_tuning \
    imx576_mipi_raw_IdxMgr \
    imx576_mipi_raw_tuning \
    imx586_mipi_raw_IdxMgr \
    imx586_mipi_raw_tuning \
    lib3a.ae.core \
    lib3a.ae \
    lib3a.af.core \
    lib3a.af \
    lib3a.awb.core \
    lib3a.awb \
    lib3a.ccudrv \
    lib3a.ccuif \
    lib3a.flash \
    lib3a.gma \
    lib3a.lce \
    lib3a.log \
    lib3a.n3d3a \
    libCamera_gc02m1bmipimono20730_Capture_Preview \
    libCamera_gc02m1bmipimono20730_Default_Video \
    libCamera_gc02m1bmipimono20730_Production_Capture \
    libCamera_gc02m1bmipimono20730_Reserved \
    libCamera_gc02m1bmipimono20730_Scene_Capture \
    libCamera_gc02m1mipiraw20730_Reserved \
    libCamera_gc02m1mipiraw20730_Scene_Capture \
    libCamera_gc02m1mipiraw20730_Scene_Preview \
    libCamera_imx350mipiraw_AutoHDR_Capture \
    libCamera_imx350mipiraw_AutoHDR_Preview \
    libCamera_imx350mipiraw_AutoHDR_Video \
    libCamera_imx350mipiraw_Face_Capture \
    libCamera_imx350mipiraw_Flash_Capture \
    libCamera_imx350mipiraw_Flash_HDR_Capture \
    libCamera_imx350mipiraw_HDR_Capture \
    libCamera_imx350mipiraw_HDR_Preview \
    libCamera_imx350mipiraw_HDR_Video \
    libCamera_imx350mipiraw_N3D_Capture \
    libCamera_imx350mipiraw_N3D_Preview \
    libCamera_imx350mipiraw_N3D_Video \
    libCamera_imx350mipiraw_Reserved \
    libCamera_imx350mipiraw_Scene_Capture \
    libCamera_imx350mipiraw_Scene_Capture_4cell \
    libCamera_imx350mipiraw_Scene_Preview \
    libCamera_imx350mipiraw_Scene_Preview_4k \
    libCamera_imx350mipiraw_Scene_Preview_ZSD_Flash \
    libCamera_imx350mipiraw_Video_1080 \
    libCamera_imx350mipiraw_Video_4k \
    libCamera_imx386mipimono_AutoHDR_Capture \
    libCamera_imx386mipimono_AutoHDR_Preview \
    libCamera_imx386mipimono_AutoHDR_Video \
    libCamera_imx386mipimono_Face_Capture \
    libCamera_imx386mipimono_Flash_Capture \
    libCamera_imx386mipimono_Flash_HDR_Capture \
    libCamera_imx386mipimono_HDR_Capture \
    libCamera_imx386mipimono_HDR_Preview \
    libCamera_imx386mipimono_HDR_Video \
    libCamera_imx386mipimono_N3D_Capture \
    libCamera_imx386mipimono_N3D_Preview \
    libCamera_imx386mipimono_N3D_Video \
    libCamera_imx386mipimono_Reserved \
    libCamera_imx386mipimono_Scene_Capture \
    libCamera_imx386mipimono_Scene_Capture_4cell \
    libCamera_imx386mipimono_Scene_Preview \
    libCamera_imx386mipimono_Scene_Preview_4k \
    libCamera_imx386mipimono_Scene_Preview_ZSD_Flash \
    libCamera_imx386mipimono_Video_1080 \
    libCamera_imx386mipimono_Video_4k \
    libCamera_imx386mipiraw_AutoHDR_Capture \
    libCamera_imx386mipiraw_AutoHDR_Preview \
    libCamera_imx386mipiraw_AutoHDR_Video \
    libCamera_imx386mipiraw_Face_Capture \
    libCamera_imx386mipiraw_Flash_Capture \
    libCamera_imx386mipiraw_Flash_HDR_Capture \
    libCamera_imx386mipiraw_HDR_Capture \
    libCamera_imx386mipiraw_HDR_Preview \
    libCamera_imx386mipiraw_HDR_Video \
    libCamera_imx386mipiraw_N3D_Capture \
    libCamera_imx386mipiraw_N3D_Preview \
    libCamera_imx386mipiraw_N3D_Video \
    libCamera_imx386mipiraw_Reserved \
    libCamera_imx386mipiraw_Scene_Capture \
    libCamera_imx386mipiraw_Scene_Capture_4cell \
    libCamera_imx386mipiraw_Scene_Preview \
    libCamera_imx386mipiraw_Scene_Preview_4k \
    libCamera_imx386mipiraw_Scene_Preview_ZSD_Flash \
    libCamera_imx386mipiraw_Video_1080 \
    libCamera_imx386mipiraw_Video_4k \
    libCamera_imx398mipiraw_AutoHDR_Capture \
    libCamera_imx398mipiraw_AutoHDR_Preview \
    libCamera_imx398mipiraw_AutoHDR_Video \
    libCamera_imx398mipiraw_Face_Capture \
    libCamera_imx398mipiraw_Flash_Capture \
    libCamera_imx398mipiraw_Flash_HDR_Capture \
    libCamera_imx398mipiraw_HDR_Capture \
    libCamera_imx398mipiraw_HDR_Preview \
    libCamera_imx398mipiraw_HDR_Video \
    libCamera_imx398mipiraw_N3D_Capture \
    libCamera_imx398mipiraw_N3D_Preview \
    libCamera_imx398mipiraw_N3D_Video \
    libCamera_imx398mipiraw_Reserved \
    libCamera_imx398mipiraw_Scene_Capture \
    libCamera_imx398mipiraw_Scene_Capture_4cell \
    libCamera_imx398mipiraw_Scene_Preview \
    libCamera_imx398mipiraw_Scene_Preview_4k \
    libCamera_imx398mipiraw_Scene_Preview_ZSD_Flash \
    libCamera_imx398mipiraw_Video_1080 \
    libCamera_imx398mipiraw_Video_4k \
    libCamera_imx471mipiraw220730_3HDR_Preivew \
    libCamera_imx471mipiraw220730_3rd_Capture_1080P \
    libCamera_imx471mipiraw220730_3rd_Capture_480P \
    libCamera_imx471mipiraw220730_3rd_Capture_720P \
    libCamera_imx471mipiraw220730_3rd_Preview_1080P \
    libCamera_imx471mipiraw220730_3rd_Preview_480P \
    libCamera_imx471mipiraw220730_3rd_Preview_720P \
    libCamera_imx471mipiraw220730_FaceBeauty_Capture \
    libCamera_imx471mipiraw220730_FaceBeauty_Preview_Noface \
    libCamera_imx471mipiraw220730_FaceBeauty_Scene_Preview \
    libCamera_imx471mipiraw220730_FaceUnlock \
    libCamera_imx471mipiraw220730_Face_Capture \
    libCamera_imx471mipiraw220730_Face_Capture_superNS \
    libCamera_imx471mipiraw220730_Flash_Capture \
    libCamera_imx471mipiraw220730_PIP_Scene \
    libCamera_imx471mipiraw220730_Panorama \
    libCamera_imx471mipiraw220730_Production_Capture \
    libCamera_imx471mipiraw220730_Reserved \
    libCamera_imx471mipiraw220730_Scene_Capture \
    libCamera_imx471mipiraw220730_Scene_Capture_Bining \
    libCamera_imx471mipiraw220730_Scene_Preview \
    libCamera_imx471mipiraw220730_SlowMotion_Video \
    libCamera_imx471mipiraw220730_Video_Recording \
    libCamera_imx471mipiraw220730_WeChatQQ_1080P \
    libCamera_imx471mipiraw220730_WeChatQQ_480P \
    libCamera_imx471mipiraw220730_WeChatQQ_720P \
    libCamera_imx471mipiraw220730_YUVHDR_Capture \
    libCamera_imx471mipiraw220730_YUVHDR_Capture_Binning \
    libCamera_imx471mipiraw220730_subject_capture \
    libCamera_imx471mipiraw220730_zHDR_Capture_Binning \
    libCamera_imx499mipiraw_AutoHDR_Capture \
    libCamera_imx499mipiraw_AutoHDR_Preview \
    libCamera_imx499mipiraw_AutoHDR_Video \
    libCamera_imx499mipiraw_Face_Capture \
    libCamera_imx499mipiraw_Flash_Capture \
    libCamera_imx499mipiraw_Flash_HDR_Capture \
    libCamera_imx499mipiraw_HDR_Capture \
    libCamera_imx499mipiraw_HDR_Preview \
    libCamera_imx499mipiraw_HDR_Video \
    libCamera_imx499mipiraw_N3D_Capture \
    libCamera_imx499mipiraw_N3D_Preview \
    libCamera_imx499mipiraw_N3D_Video \
    libCamera_imx499mipiraw_Reserved \
    libCamera_imx499mipiraw_Scene_Capture \
    libCamera_imx499mipiraw_Scene_Capture_4cell \
    libCamera_imx499mipiraw_Scene_Preview \
    libCamera_imx499mipiraw_Scene_Preview_4k \
    libCamera_imx499mipiraw_Scene_Preview_ZSD_Flash \
    libCamera_imx499mipiraw_Video_1080 \
    libCamera_imx499mipiraw_Video_4k \
    libCamera_imx519mipiraw_AutoHDR_Capture \
    libCamera_imx519mipiraw_AutoHDR_Preview \
    libCamera_imx519mipiraw_AutoHDR_Video \
    libCamera_imx519mipiraw_Face_Capture \
    libCamera_imx519mipiraw_Flash_Capture \
    libCamera_imx519mipiraw_Flash_HDR_Capture \
    libCamera_imx519mipiraw_HDR_Capture \
    libCamera_imx519mipiraw_HDR_Preview \
    libCamera_imx519mipiraw_HDR_Video \
    libCamera_imx519mipiraw_N3D_Capture \
    libCamera_imx519mipiraw_N3D_Preview \
    libCamera_imx519mipiraw_N3D_Video \
    libCamera_imx519mipiraw_Reserved \
    libCamera_imx519mipiraw_Scene_Capture \
    libCamera_imx519mipiraw_Scene_Capture_4cell \
    libCamera_imx519mipiraw_Scene_Preview \
    libCamera_imx519mipiraw_Scene_Preview_4k \
    libCamera_imx519mipiraw_Scene_Preview_ZSD_Flash \
    libCamera_imx519mipiraw_Video_1080 \
    libCamera_imx519mipiraw_Video_4k \
    libCamera_imx576mipiraw_AutoHDR_Capture \
    libCamera_imx576mipiraw_AutoHDR_Preview \
    libCamera_imx576mipiraw_AutoHDR_Video \
    libCamera_imx576mipiraw_Face_Capture \
    libCamera_imx576mipiraw_Flash_Capture \
    libCamera_imx576mipiraw_Flash_HDR_Capture \
    libCamera_imx576mipiraw_HDR_Capture \
    libCamera_imx576mipiraw_HDR_Preview \
    libCamera_imx576mipiraw_HDR_Video \
    libCamera_imx576mipiraw_N3D_Capture \
    libCamera_imx576mipiraw_N3D_Preview \
    libCamera_imx576mipiraw_N3D_Video \
    libCamera_imx576mipiraw_Reserved \
    libCamera_imx576mipiraw_Scene_Capture \
    libCamera_imx576mipiraw_Scene_Capture_4cell \
    libCamera_imx576mipiraw_Scene_Preview \
    libCamera_imx576mipiraw_Scene_Preview_4k \
    libCamera_imx576mipiraw_Scene_Preview_ZSD_Flash \
    libCamera_imx576mipiraw_Video_1080 \
    libCamera_imx576mipiraw_Video_4k \
    libCamera_imx586mipiraw_AutoHDR_Capture \
    libCamera_imx586mipiraw_AutoHDR_Preview \
    libCamera_imx586mipiraw_AutoHDR_Video \
    libCamera_imx586mipiraw_Face_Capture \
    libCamera_imx586mipiraw_Flash_Capture \
    libCamera_imx586mipiraw_Flash_HDR_Capture \
    libCamera_imx586mipiraw_HDR_Capture \
    libCamera_imx586mipiraw_HDR_Preview \
    libCamera_imx586mipiraw_HDR_Video \
    libCamera_imx586mipiraw_N3D_Capture \
    libCamera_imx586mipiraw_N3D_Preview \
    libCamera_imx586mipiraw_N3D_Video \
    libCamera_imx586mipiraw_Reserved \
    libCamera_imx586mipiraw_Scene_Capture \
    libCamera_imx586mipiraw_Scene_Capture_4cell \
    libCamera_imx586mipiraw_Scene_Preview \
    libCamera_imx586mipiraw_Scene_Preview_4k \
    libCamera_imx586mipiraw_Scene_Preview_ZSD_Flash \
    libCamera_imx586mipiraw_Video_1080 \
    libCamera_imx586mipiraw_Video_4k \
    libCamera_ov64bmipiraw20730_3rd_Capture_1080P \
    libCamera_ov64bmipiraw20730_3rd_Capture_480P \
    libCamera_ov64bmipiraw20730_3rd_Capture_720P \
    libCamera_ov64bmipiraw20730_Capture_Preview \
    libCamera_ov64bmipiraw20730_Capture_Preview_Zoom \
    libCamera_ov64bmipiraw20730_FaceBeauty_Capture \
    libCamera_ov64bmipiraw20730_Face_Capture \
    libCamera_ov64bmipiraw20730_Face_Capture_64M \
    libCamera_ov64bmipiraw20730_Face_Preview \
    libCamera_ov64bmipiraw20730_Face_SuperNight_Hand_Capture \
    libCamera_ov64bmipiraw20730_Face_SuperNight_Hand_Capture_Zoom \
    libCamera_ov64bmipiraw20730_Face_SuperNight_Hand_Preview_Zoom \
    libCamera_ov64bmipiraw20730_Flash_Capture \
    libCamera_ov64bmipiraw20730_HDR_Capture \
    libCamera_ov64bmipiraw20730_Panorama_Capture \
    libCamera_ov64bmipiraw20730_Production_Capture \
    libCamera_ov64bmipiraw20730_Professional_Capture \
    libCamera_ov64bmipiraw20730_Reserved \
    libCamera_ov64bmipiraw20730_Scene_Capture \
    libCamera_ov64bmipiraw20730_Scene_Capture_64M \
    libCamera_ov64bmipiraw20730_Scene_Capture_Food \
    libCamera_ov64bmipiraw20730_Scene_Preview \
    libCamera_ov64bmipiraw20730_StarMode_Capture \
    libCamera_ov64bmipiraw20730_StarMode_Preview \
    libCamera_ov64bmipiraw20730_SuperNight_Hand_Capture \
    libCamera_ov64bmipiraw20730_SuperNight_Hand_Capture_Zoom \
    libCamera_ov64bmipiraw20730_SuperNight_Hand_Preview_Zoom \
    libCamera_ov64bmipiraw20730_SuperNight_Tripod_Capture \
    libCamera_ov64bmipiraw20730_SuperNight_Tripod_Capture_Zoom \
    libCamera_ov64bmipiraw20730_TimeLapse_video \
    libCamera_ov64bmipiraw20730_Video_1080p_120fps \
    libCamera_ov64bmipiraw20730_Video_30fps \
    libCamera_ov64bmipiraw20730_Video_30fps_5x \
    libCamera_ov64bmipiraw20730_Video_4k_30fps \
    libCamera_ov64bmipiraw20730_Video_60fps \
    libCamera_ov64bmipiraw20730_Video_60fps_5x \
    libCamera_ov64bmipiraw20730_Video_720p_240fps \
    libCamera_ov64bmipiraw20730_Video_Capture \
    libCamera_ov64bmipiraw20730_Video_Movie \
    libCamera_ov64bmipiraw20730_Video_Preview \
    libCamera_ov64bmipiraw20730_Zoom_Capture \
    libCamera_ov64bmipiraw20730_Zoom_Capture_2x \
    libCamera_ov64bmipiraw20730_Zoom_Capture_Face_2x \
    libCamera_ov64bmipiraw20730_Zoom_Preview \
    libCamera_ov64bmipiraw20730_portrait_capture_full \
    libCamera_ov64bmipiraw20730_portrait_preview_full \
    libCamera_ov8856mipiraw220730_AutoHDR_Capture \
    libCamera_ov8856mipiraw220730_AutoHDR_Preview \
    libCamera_ov8856mipiraw220730_AutoHDR_Video \
    libCamera_ov8856mipiraw220730_Face_Capture \
    libCamera_ov8856mipiraw220730_Face_Capture_superNS \
    libCamera_ov8856mipiraw220730_Flash_Capture \
    libCamera_ov8856mipiraw220730_Flash_HDR_Capture \
    libCamera_ov8856mipiraw220730_HDR_Capture \
    libCamera_ov8856mipiraw220730_HDR_Preview \
    libCamera_ov8856mipiraw220730_HDR_Video \
    libCamera_ov8856mipiraw220730_N3D_Capture \
    libCamera_ov8856mipiraw220730_N3D_Capture_48M \
    libCamera_ov8856mipiraw220730_N3D_Preview \
    libCamera_ov8856mipiraw220730_N3D_Preview_48M \
    libCamera_ov8856mipiraw220730_N3D_Video \
    libCamera_ov8856mipiraw220730_Professional_Capture \
    libCamera_ov8856mipiraw220730_Reserved \
    libCamera_ov8856mipiraw220730_Scene_Capture \
    libCamera_ov8856mipiraw220730_Scene_Capture_4cell \
    libCamera_ov8856mipiraw220730_Scene_Capture_superNS \
    libCamera_ov8856mipiraw220730_Scene_Preview \
    libCamera_ov8856mipiraw220730_Scene_Preview_ZSD_Flash \
    libCamera_ov8856mipiraw220730_Scene_Preview_ZSD_superNS \
    libCamera_ov8856mipiraw220730_Video_1080 \
    libCamera_ov8856mipiraw220730_Video_4k \
    libCamera_s5k2l7mipiraw_AutoHDR_Capture \
    libCamera_s5k2l7mipiraw_AutoHDR_Preview \
    libCamera_s5k2l7mipiraw_AutoHDR_Video \
    libCamera_s5k2l7mipiraw_Face_Capture \
    libCamera_s5k2l7mipiraw_Flash_Capture \
    libCamera_s5k2l7mipiraw_Flash_HDR_Capture \
    libCamera_s5k2l7mipiraw_HDR_Capture \
    libCamera_s5k2l7mipiraw_HDR_Preview \
    libCamera_s5k2l7mipiraw_HDR_Video \
    libCamera_s5k2l7mipiraw_N3D_Capture \
    libCamera_s5k2l7mipiraw_N3D_Preview \
    libCamera_s5k2l7mipiraw_N3D_Video \
    libCamera_s5k2l7mipiraw_Reserved \
    libCamera_s5k2l7mipiraw_Scene_Capture \
    libCamera_s5k2l7mipiraw_Scene_Capture_4cell \
    libCamera_s5k2l7mipiraw_Scene_Preview \
    libCamera_s5k2l7mipiraw_Scene_Preview_4k \
    libCamera_s5k2l7mipiraw_Scene_Preview_ZSD_Flash \
    libCamera_s5k2l7mipiraw_Video_1080 \
    libCamera_s5k2l7mipiraw_Video_4k \
    libCamera_s5k2lqsxmipiraw_AutoHDR_Capture \
    libCamera_s5k2lqsxmipiraw_AutoHDR_Preview \
    libCamera_s5k2lqsxmipiraw_AutoHDR_Video \
    libCamera_s5k2lqsxmipiraw_Face_Capture \
    libCamera_s5k2lqsxmipiraw_Flash_Capture \
    libCamera_s5k2lqsxmipiraw_Flash_HDR_Capture \
    libCamera_s5k2lqsxmipiraw_HDR_Capture \
    libCamera_s5k2lqsxmipiraw_HDR_Preview \
    libCamera_s5k2lqsxmipiraw_HDR_Video \
    libCamera_s5k2lqsxmipiraw_N3D_Capture \
    libCamera_s5k2lqsxmipiraw_N3D_Preview \
    libCamera_s5k2lqsxmipiraw_N3D_Video \
    libCamera_s5k2lqsxmipiraw_Reserved \
    libCamera_s5k2lqsxmipiraw_Scene_Capture \
    libCamera_s5k2lqsxmipiraw_Scene_Capture_4cell \
    libCamera_s5k2lqsxmipiraw_Scene_Preview \
    libCamera_s5k2lqsxmipiraw_Scene_Preview_4k \
    libCamera_s5k2lqsxmipiraw_Scene_Preview_ZSD_Flash \
    libCamera_s5k2lqsxmipiraw_Video_1080 \
    libCamera_s5k2lqsxmipiraw_Video_4k \
    libCamera_s5k2t7spmipiraw_AutoHDR_Capture \
    libCamera_s5k2t7spmipiraw_AutoHDR_Preview \
    libCamera_s5k2t7spmipiraw_AutoHDR_Video \
    libCamera_s5k2t7spmipiraw_Face_Capture \
    libCamera_s5k2t7spmipiraw_Flash_Capture \
    libCamera_s5k2t7spmipiraw_Flash_HDR_Capture \
    libCamera_s5k2t7spmipiraw_HDR_Capture \
    libCamera_s5k2t7spmipiraw_HDR_Preview \
    libCamera_s5k2t7spmipiraw_HDR_Video \
    libCamera_s5k2t7spmipiraw_N3D_Capture \
    libCamera_s5k2t7spmipiraw_N3D_Preview \
    libCamera_s5k2t7spmipiraw_N3D_Video \
    libCamera_s5k2t7spmipiraw_Reserved \
    libCamera_s5k2t7spmipiraw_Scene_Capture \
    libCamera_s5k2t7spmipiraw_Scene_Capture_4cell \
    libCamera_s5k2t7spmipiraw_Scene_Preview \
    libCamera_s5k2t7spmipiraw_Scene_Preview_4k \
    libCamera_s5k2t7spmipiraw_Scene_Preview_ZSD_Flash \
    libCamera_s5k2t7spmipiraw_Video_1080 \
    libCamera_s5k2t7spmipiraw_Video_4k \
    libCamera_s5k4h7mipiraw_AutoHDR_Capture \
    libCamera_s5k4h7mipiraw_AutoHDR_Preview \
    libCamera_s5k4h7mipiraw_AutoHDR_Video \
    libCamera_s5k4h7mipiraw_Face_Capture \
    libCamera_s5k4h7mipiraw_Flash_Capture \
    libCamera_s5k4h7mipiraw_Flash_HDR_Capture \
    libCamera_s5k4h7mipiraw_HDR_Capture \
    libCamera_s5k4h7mipiraw_HDR_Preview \
    libCamera_s5k4h7mipiraw_HDR_Video \
    libCamera_s5k4h7mipiraw_N3D_Capture \
    libCamera_s5k4h7mipiraw_N3D_Preview \
    libCamera_s5k4h7mipiraw_N3D_Video \
    libCamera_s5k4h7mipiraw_Reserved \
    libCamera_s5k4h7mipiraw_Scene_Capture \
    libCamera_s5k4h7mipiraw_Scene_Capture_4cell \
    libCamera_s5k4h7mipiraw_Scene_Preview \
    libCamera_s5k4h7mipiraw_Scene_Preview_4k \
    libCamera_s5k4h7mipiraw_Scene_Preview_ZSD_Flash \
    libCamera_s5k4h7mipiraw_Video_1080 \
    libCamera_s5k4h7mipiraw_Video_4k \
    libCamera_s5khm2spmipiraw_108M_Capture \
    libCamera_s5khm2spmipiraw_108M_Flash_Capture \
    libCamera_s5khm2spmipiraw_AutoHDR_Capture \
    libCamera_s5khm2spmipiraw_AutoHDR_Preview \
    libCamera_s5khm2spmipiraw_AutoHDR_Video \
    libCamera_s5khm2spmipiraw_Face_Capture \
    libCamera_s5khm2spmipiraw_Flash_Capture \
    libCamera_s5khm2spmipiraw_Flash_HDR_Capture \
    libCamera_s5khm2spmipiraw_HDR_Capture \
    libCamera_s5khm2spmipiraw_HDR_Preview \
    libCamera_s5khm2spmipiraw_HDR_Video \
    libCamera_s5khm2spmipiraw_N3D_Capture \
    libCamera_s5khm2spmipiraw_N3D_Preview \
    libCamera_s5khm2spmipiraw_N3D_Video \
    libCamera_s5khm2spmipiraw_Reserved \
    libCamera_s5khm2spmipiraw_Scene_Capture \
    libCamera_s5khm2spmipiraw_Scene_Capture_4cell \
    libCamera_s5khm2spmipiraw_Scene_Preview \
    libCamera_s5khm2spmipiraw_Scene_Preview_4k \
    libCamera_s5khm2spmipiraw_Scene_Preview_ZSD_Flash \
    libCamera_s5khm2spmipiraw_Video_1080 \
    libCamera_s5khm2spmipiraw_Video_4k \
    libDR \
    libDefaultFpsActor \
    libFrameRecord \
    libJpgEncPipe \
    libMcClient \
    libNoFpsActor \
    libOpenCL \
    libSQLiteModule_VER_ALL \
    libSonyIMX230PdafLibrary \
    libSonyIMX230PdafLibraryWrapper \
    libSonyIMX338PdafLibrary \
    libSonyIMX338PdafLibraryWrapper \
    libSonyIMX386PdafLibrary \
    libSonyIMX386PdafLibraryWrapper \
    libSonyIMX519PdafLibrary \
    libSonyIMX519PdafLibraryWrapper \
    lib_bsscore \
    libaal_cust \
    libaal_key \
    libaal_mtk \
    libaalservice \
    libadpcmdec_mtk \
    libakm \
    libapu_mdw \
    libapusys \
    libarmnn \
    libarmnn_ndk.mtk.vndk \
    libasn1c_core \
    libasn1c_mapi \
    libasn1c_mdmi \
    libbluetooth_mtk \
    libbluetooth_mtk_pure \
    libbt-vendor \
    libcam.chdr \
    libcam.feature_utils \
    libcam.hal3a.cctsvr \
    libcam.hal3a.log \
    libcam.hal3a.v3.dng \
    libcam.hal3a.v3.lscMgr \
    libcam.hal3a.v3.lsctbl.50 \
    libcam.hal3a.v3.nvram.50 \
    libcam.hal3a.v3 \
    libcam.halisp \
    libcam.halsensor \
    libcam.iopipe \
    libcam.lcs \
    libcam.pdtblgen \
    libcam.utils.sensorprovider \
    libcam.vhdr \
    libcamalgo.3dnr \
    libcamalgo.dngop \
    libcamalgo.eis \
    libcamalgo.fdft \
    libcamalgo.flicker \
    libcamalgo.fsc \
    libcamalgo.gyro \
    libcamalgo.ispfeature \
    libcamalgo.lmv \
    libcamalgo.lsc \
    libcamalgo.mfnr \
    libcamalgo.n3d \
    libcamalgo.platform \
    libcamalgo.platform2 \
    libcamalgo.utility \
    libcamalgo.vpunr \
    libcamalgo.vsf \
    libcamalgo.warp \
    libcamdrv_imem \
    libcamdrv_isp \
    libcamdrv_tuning_mgr \
    libcamdrv_twin \
    libcamera_core_hwi \
    libcameracustom.eis \
    libcameracustom.plugin \
    libcameracustom \
    libcares_naptr \
    libcarrierconfig \
    libccci_util \
    libchromanr \
    libcmdl \
    libcmdl_ndk.mtk.vndk \
    libcodec2_mtk_c2store \
    libcodec2_mtk_vdec \
    libcodec2_mtk_venc \
    libcodec2_soft_mtk_alacdec \
    libcodec2_soft_mtk_apedec \
    libcodec2_soft_mtk_imaadpcmdec \
    libcodec2_soft_mtk_mp3dec \
    libcodec2_soft_mtk_msadpcmdec \
    libcodec2_soft_mtk_wmadec \
    libcodec2_vpp_qt_plugin \
    libcodec2_vpp_rs_plugin \
    libcomposer_ext \
    libconnfem \
    libcustomer_cameradata \
    libcustomer_testvision \
    libdip_drv \
    libdip_imem \
    libdip_postproc \
    libdre \
    libeffecthal.base \
    libfeature.face \
    libfeature.stereo.provider \
    libfeature.vsdof.hal \
    libfeature_3dnr \
    libfeature_eis \
    libfeature_fsc \
    libfeature_lmv \
    libfeature_rss \
    libfeatureiodrv_mem \
    libforkexecwrap \
    libformatter \
    libgamehdr \
    libged \
    libgpu_aux \
    libgpud \
    libgralloc_extra \
    libgralloc_metadata \
    libgralloctypes_mtk \
    libgz_gp_client \
    libgz_uree \
    libhdrvideo \
    libheichal \
    libhwconfigurationutil \
    libhwm-oplus \
    libhwm \
    libifcutils_mtk \
    libimageio \
    libimageio_plat_drv \
    libimageio_plat_pipe \
    libispcameraca \
    libjpeg-alpha-oal_vendor \
    libjpeg-alpha_vendor \
    libksensor \
    liblpcnr \
    libmfllcore \
    libmidasserviceintf \
    libmipc \
    libmml \
    libmnetlink_v104 \
    libmnl \
    libmp3dec_mtk \
    libmsnr \
    libmtcloader \
    libmtk-ril \
    libmtkares \
    libmtkcam.atmseventmgr \
    libmtkcam.eventcallback \
    libmtkcam.featurepipe.capture \
    libmtkcam.featurepipe.depthmap \
    libmtkcam.featurepipe.streaming \
    libmtkcam.featurepipe.vsdof_util \
    libmtkcam.logicalmodule \
    libmtkcam_3rdparty.core \
    libmtkcam_3rdparty.customer \
    libmtkcam_3rdparty.mtk \
    libmtkcam_3rdparty \
    libmtkcam_calibration_convertor \
    libmtkcam_calibration_provider \
    libmtkcam_debugutils \
    libmtkcam_device3_app \
    libmtkcam_device3_hal \
    libmtkcam_device3_hidl \
    libmtkcam_device3_hidlutils \
    libmtkcam_device3_utils \
    libmtkcam_devicesessionpolicy \
    libmtkcam_diputils \
    libmtkcam_dpe \
    libmtkcam_exif \
    libmtkcam_fdvt \
    libmtkcam_featurepolicy \
    libmtkcam_featureutils \
    libmtkcam_fwkutils \
    libmtkcam_grallocutils \
    libmtkcam_hwnode \
    libmtkcam_hwutils \
    libmtkcam_imgbuf \
    libmtkcam_mapping_mgr \
    libmtkcam_metadata \
    libmtkcam_metastore \
    libmtkcam_mfb \
    libmtkcam_modulefactory_aaa \
    libmtkcam_modulefactory_custom \
    libmtkcam_modulefactory_drv \
    libmtkcam_modulefactory_utils \
    libmtkcam_modulehelper \
    libmtkcam_owe \
    libmtkcam_pipeline \
    libmtkcam_pipeline_fbm \
    libmtkcam_pipelinemodel \
    libmtkcam_pipelinemodel_adapter \
    libmtkcam_pipelinemodel_capture \
    libmtkcam_pipelinemodel_isp \
    libmtkcam_pipelinemodel_session \
    libmtkcam_pipelinemodel_utils \
    libmtkcam_pipelinemodel_zsl \
    libmtkcam_pipelinepolicy-aov \
    libmtkcam_pipelinepolicy-security \
    libmtkcam_pipelinepolicy-smvr \
    libmtkcam_pipelinepolicy \
    libmtkcam_pipelinepolicy_factory \
    libmtkcam_prerelease \
    libmtkcam_rsc \
    libmtkcam_scenariorecorder \
    libmtkcam_stdutils \
    libmtkcam_streamutils \
    libmtkcam_synchelper \
    libmtkcam_sysutils \
    libmtkcam_tuning_utils \
    libmtkcam_ulog \
    libmtkconfig \
    libmtkconfigutils \
    libmtkhardware_legacy \
    libmtkisp_metadata \
    libmtknetcap \
    libmtknetutils \
    libmtkrilutils \
    libmtksysutils \
    libmtktinyxml \
    libmtkutils \
    libneuron_adapter \
    libneuron_graph_delegate.mtk \
    libneuron_platform \
    libneuropilot_hal_utils \
    libnir_neon_driver_ndk.mtk.vndk \
    libocam_common \
    liboplus.aishutter \
    liboplus_mtkcam_lightsensorprovider \
    liboppo_arcSoftBokehEngine \
    libpn557_fw \
    libpq_cust_base \
    libpqframework \
    libpqparamparser \
    libpqpconfig \
    libratconfig \
    libremosaic_wrapper \
    libremosaiclib \
    librilfusion \
    libsensor_custom \
    libstereoinfoaccessor_vsdof \
    libstorage_otp \
    libsysenv \
    libtlcWidevineModularDrm \
    libtrm \
    libudf \
    liburee_meta_drmkeyinstall \
    libvow_ap_test_aa \
    libvow_ap_test_dd \
    libvow_ap_test_ha \
    libvow_ap_test_hh \
    libvow_ap_test_nn \
    libwifi-hal-mtk \
    libwpfa \
    libwvhidl \
    libwvdrmengine \
    libdpframework \
    libneuron_runtime.5 \
    libneuron_runtime \
    libnir_neon_driver \
    libpq_prot \
    libmtkcam_streaminfo_plugin-p1stt \
    ov64b_mipi_raw_20730_IdxMgr \
    ov64b_mipi_raw_20730_tuning \
    ov8856_mipi_raw2_20730_IdxMgr \
    ov8856_mipi_raw2_20730_tuning \
    s5k2l7_mipi_raw_IdxMgr \
    s5k2l7_mipi_raw_tuning \
    s5k2lqsx_mipi_raw_IdxMgr \
    s5k2lqsx_mipi_raw_tuning \
    s5k2t7sp_mipi_raw_IdxMgr \
    s5k2t7sp_mipi_raw_tuning \
    s5k4h7_mipi_raw_IdxMgr \
    s5k4h7_mipi_raw_tuning \
    s5khm2sp_mipi_raw_IdxMgr \
    s5khm2sp_mipi_raw_tuning \
    vendor.mediatek.hardware.apuware.utils@2.0 \
    vendor.mediatek.hardware.camera.atms@1.0 \
    vendor.mediatek.hardware.camera.bgservice@1.0 \
    vendor.mediatek.hardware.camera.bgservice@1.1 \
    vendor.mediatek.hardware.camera.ccap@1.0 \
    vendor.mediatek.hardware.camera.frhandler@1.0 \
    vendor.mediatek.hardware.camera.isphal@1.0 \
    vendor.mediatek.hardware.camera.isphal@1.1 \
    vendor.mediatek.hardware.camera.lomoeffect@1.0 \
    vendor.mediatek.hardware.camera.postproc@1.0 \
    vendor.mediatek.hardware.camera.security@1.0 \
    vendor.mediatek.hardware.clientapi@1.0 \
    vendor.mediatek.hardware.composer_ext@1.0 \
    vendor.mediatek.hardware.mmagent@1.0 \
    vendor.mediatek.hardware.mmagent@1.1 \
    vendor.mediatek.hardware.mms@1.0 \
    vendor.mediatek.hardware.mms@1.1 \
    vendor.mediatek.hardware.mms@1.2 \
    vendor.mediatek.hardware.mms@1.3 \
    vendor.mediatek.hardware.mms@1.4 \
    vendor.mediatek.hardware.mms@1.5 \
    vendor.mediatek.hardware.mms@1.6 \
    vendor.mediatek.hardware.mtkradioex@2.0 \
    vendor.mediatek.hardware.mtkradioex@3.0 \
    vendor.mediatek.hardware.netdagent@1.0 \
    vendor.mediatek.hardware.power@2.0 \
    vendor.mediatek.hardware.pq@2.0 \
    vendor.mediatek.hardware.pq@2.1 \
    vendor.mediatek.hardware.pq@2.10 \
    vendor.mediatek.hardware.pq@2.11 \
    vendor.mediatek.hardware.pq@2.12 \
    vendor.mediatek.hardware.pq@2.13 \
    vendor.mediatek.hardware.pq@2.14 \
    vendor.mediatek.hardware.pq@2.15 \
    vendor.mediatek.hardware.pq@2.2 \
    vendor.mediatek.hardware.pq@2.3 \
    vendor.mediatek.hardware.pq@2.4 \
    vendor.mediatek.hardware.pq@2.5 \
    vendor.mediatek.hardware.pq@2.6 \
    vendor.mediatek.hardware.pq@2.7 \
    vendor.mediatek.hardware.pq@2.8 \
    vendor.mediatek.hardware.pq@2.9 \
    vendor.oplus.hardware.cameraextension@1.0 \
    vendor.oplus.hardware.cammidasservice@1.0 \
    vendor.oplus.hardware.performance-V1-ndk_platform \
    vendor.oplus.hardware.radio-V1-ndk_platform \
    libcomutils \
    libimsma \
    libimsma_adapt \
    libimsma_rtp \
    libimsma_socketwrapper \
    libmtk_vt_service \
    libmtk_vt_wrapper \
    libsignal \
    libsink-mtk \
    libsource \
    libvcodec_cap \
    libvcodec_capenc \
    libvt_avsync \
    vendor.mediatek.hardware.videotelephony-V1-ndk \
    vendor.mediatek.hardware.videotelephony@1.0 \
    libpnscr2 \
    libawinicsmartpaparse \
    anc.capacitive.hal \
    anc.hal \
    fingerprint.goodix_G2.default \
    fingerprint.goodix_G3.default \
    fingerprint.goodix_G5.default \
    fingerprint.goodix_G6.default \
    fingerprint.goodix_G7.default \
    libgf_hal_G2 \
    libgf_hal_G3 \
    libgf_hal_G5 \
    libgf_hal_G6 \
    libgf_hal_G7 \
    libmpbase \
    liboemcrypto \
    liboplus_platform_hwi \
    libormshalclient \
    libosenseaidlhalclient \
    libosensehalclient \
    vendor.oplus.hardware.appradio@1.0 \
    vendor.oplus.hardware.charger@1.0 \
    vendor.oplus.hardware.commondcs@1.0 \
    vendor.oplus.hardware.engcamera@1.0 \
    vendor.oplus.hardware.oplusSensor@1.0 \
    vendor.oplus.hardware.orms@1.0 \
    vendor.oplus.hardware.osense.client@1.0 \
    ImsService \
    mediatek-common \
    mediatek-framework \
    mediatek-ims-base \
    mediatek-ims-common \
    mediatek-ims-extension-plugin \
    android.hardware.neuralnetworks@1.3-service-mtk-dsp-gpu.xml \
    gnss-mtk.xml \
    gnss@2.1-service.xml \
    manifest_android.hardware.drm@1.4-service.widevine.xml \
    manifest_media_c2_V1_1_default.xml \
    manifest_oplusSensor.xml \
    manifest_oplus_charger.xml \
    manifest_oplus_fingerprint.xml \
    ccci_mdinit \
    ccci_rpcd \
    gsm0710muxd \
    android.hardware.bluetooth@1.1-service-mediatek \
    android.hardware.drm@1.4-service.widevine \
    android.hardware.gnss-service.mediatek \
    android.hardware.graphics.allocator@4.0-service-mediatek \
    android.hardware.keymaster@4.0-service.trustonic \
    android.hardware.media.c2@1.2-mediatek-64b \
    android.hardware.neuralnetworks@1.3-service-mtk-neuron \
    android.hardware.secure_element@1.2-service-mediatek \
    camerahalserver \
    mtkfusionrild \
    tetheroffloadservice \
    vendor.mediatek.hardware.mms@1.6-service \
    vendor.mediatek.hardware.nvram@1.1-service \
    vendor.mediatek.hardware.pq@2.2-service \
    vtservice_hidl \
    mcDriverDaemon \
    mnld \
    mtk_agpsd \
    muxreport \
    netdagent \
    nvram_daemon \
    rcs_volte_stack \
    thermal \
    thermal_manager \
    volte_clientapi_ua \
    volte_imcb \
    volte_imsm_93 \
    volte_md_status \
    volte_stack \
    volte_ua \
    vpud \
    wmt_launcher \
    wmt_loader \
    vtservice \
    vendor.oplus.hardware.biometrics.fingerprint@2.1-service \
    vendor.oplus.hardware.charger@1.0-service \
    vendor.oplus.hardware.oplusSensor@1.0-service

PRODUCT_PACKAGES += \
    vendor_bin_hw_android_hardware_media_c2@1_2-mediatek \
    vendor_lib_libmtk_drvb_so \
    vendor_lib64_hw_vulkan_mt6785_so \
    vendor_lib64_hw_gatekeeper_trustonic_so \
    vendor_lib64_libdpframework_so \
    vendor_lib64_libmtk_drvb_so \
    vendor_lib64_libneuron_runtime_5_so \
    vendor_lib64_libneuron_runtime_so \
    vendor_lib64_libnir_neon_driver_so \
    vendor_lib64_libpq_prot_so
